# Generated by Django 4.2.1 on 2023-06-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('author', '0005_alter_author_profile_pic'),
        ('article', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ArticleCategory',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='ArticlePost',
        ),
    ]
