# Generated by Django 4.2.1 on 2023-06-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_category_articlecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='tags',
            new_name='article_tags',
        ),
        migrations.RenameField(
            model_name='articlepost',
            old_name='user',
            new_name='article_users',
        ),
    ]
