# Generated by Django 4.2.1 on 2023-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_tags_articlepost_article_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
