# Generated by Django 4.2.1 on 2023-06-08 06:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='def.jpg', force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='profile_pics/'),
        ),
    ]
