# Generated by Django 4.2.1 on 2023-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_author_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='hidden_profile',
            field=models.BooleanField(default=False),
        ),
    ]
